# Generated by Django 4.0.2 on 2022-02-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndocsApp', '0003_alter_cart_product_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
