# Generated by Django 4.0.2 on 2022-02-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndocsApp', '0004_alter_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(choices=[('NP', 'Nepal'), ('IN', 'India'), ('BT', 'Both')], default='Both', max_length=2),
        ),
    ]
