# Generated by Django 4.0.2 on 2022-02-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndocsApp', '0005_product_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.CharField(choices=[('NP', 'Nepal'), ('IN', 'India'), ('BT', 'Both')], default='None', max_length=2),
        ),
    ]
