# Generated by Django 4.0.2 on 2022-02-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndocsApp', '0006_alter_product_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.CharField(choices=[('FW', 'Face Wash'), ('N', 'None')], default='None', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.CharField(choices=[('NP', 'Nepal'), ('IN', 'India'), ('BT', 'Both')], default='Both', max_length=2),
        ),
    ]
