# Generated by Django 4.0.2 on 2022-02-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndocsApp', '0008_remove_product_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.CharField(choices=[('FW', 'Face Wash'), ('PU', 'Pet Utensils'), ('N', 'None')], default='None', max_length=2),
        ),
    ]
