# Generated by Django 4.0.2 on 2022-03-16 13:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AndocsApp', '0013_extendeduser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='extendeduser',
            new_name='Profile',
        ),
    ]
