# Generated by Django 4.0.2 on 2022-03-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndocsApp', '0014_rename_extendeduser_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_num',
            field=models.CharField(default='Null', max_length=15),
        ),
    ]
