# Generated by Django 4.0.3 on 2022-09-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndocsApp', '0021_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('True', 'True'), ('False', 'False')], default='New', max_length=10),
        ),
    ]
