# Generated by Django 4.0.3 on 2022-09-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndocsApp', '0023_alter_comment_rating_alter_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(choices=[('3', '3'), ('5', '5'), ('1', '1'), ('4', '4'), ('2', '2')], default=1),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('False', 'False'), ('True', 'True'), ('New', 'New')], default='New', max_length=10),
        ),
    ]
