# Generated by Django 4.0.3 on 2022-09-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndocsApp', '0024_alter_comment_rating_alter_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(choices=[('3', '3'), ('4', '4'), ('5', '5'), ('2', '2'), ('1', '1')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Accepted', max_length=50),
        ),
    ]
