# Generated by Django 4.0.3 on 2022-09-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndocsApp', '0027_alter_comment_rating_alter_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(choices=[('3', '3'), ('4', '4'), ('1', '1'), ('5', '5'), ('2', '2')], default=1),
        ),
    ]
