# Generated by Django 4.0.3 on 2022-10-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndocsApp', '0028_alter_comment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(choices=[('1', '1'), ('5', '5'), ('2', '2'), ('3', '3'), ('4', '4')], default=1),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False'), ('New', 'New')], default='New', max_length=10),
        ),
    ]
