# Generated by Django 4.0.3 on 2022-10-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndocsApp', '0032_alter_comment_rating_alter_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.CharField(choices=[('3', '3'), ('5', '5'), ('4', '4'), ('1', '1'), ('2', '2')], default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('False', 'False'), ('New', 'New'), ('True', 'True')], default='New', max_length=10),
        ),
    ]
