# Generated by Django 4.0.3 on 2022-11-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndocsApp', '0034_alter_comment_rating_alter_comment_status_cluster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='user_name',
            field=models.CharField(default='aaravsinha', max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (5, '5'), (3, '3'), (2, '2'), (4, '4')], default='1'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False'), ('New', 'New')], default='New', max_length=10),
        ),
    ]
