# Generated by Django 4.0.3 on 2022-11-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndocsApp', '0035_remove_comment_user_comment_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(choices=[(5, '5'), (4, '4'), (2, '2'), (3, '3'), (1, '1')], default='1'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('False', 'False'), ('True', 'True')], default='New', max_length=10),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
    ]
