# Generated by Django 4.0.3 on 2022-11-26 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AndocsApp', '0036_alter_comment_rating_alter_comment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profilepic'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_set', to='AndocsApp.product'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(choices=[(4, '4'), (2, '2'), (1, '1'), (3, '3'), (5, '5')], default='1'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('True', 'True'), ('New', 'New'), ('False', 'False')], default='New', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer Not to Say', 'Prefer Not to Say')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_num',
            field=models.CharField(max_length=10),
        ),
    ]
